// <auto-generated />
using System;
using System.Collections.Generic;
using Cafeservello.Modules.Infrastructure.Users.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cafeservello.Modules.Infrastructure.Users.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cafeservello.Modules.Domain.Users.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Cafeservello.Modules.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_AT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NAME");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ID_PROFILE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("UPDATED_BY");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Cafeservello.Modules.Domain.Users.Entities.User.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("CITY");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("COMPLEMENT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("COUNTRY");

                            b1.Property<string>("Neighborhood")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("NEIGHBORHOOD");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("NUMBER");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)")
                                .HasColumnName("STATE");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("STREET");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("ZIPCODE");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "Cafeservello.Modules.Domain.Users.Entities.User.Contact#Contact", b1 =>
                        {
                            b1.Property<string>("CellPhone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("CELL_PHONE");

                            b1.Property<string>("Landline")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("LANDLINE");

                            b1.Property<string>("PrimaryEmail")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("PRIMARY_EMAIL");

                            b1.Property<string>("SecondaryEmail")
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("SECONDADARY_EMAIL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Personal", "Cafeservello.Modules.Domain.Users.Entities.User.Personal#Personal", b1 =>
                        {
                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("CPF");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("DATE_OF_BIRTH");

                            b1.Property<bool>("Gender")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("GENDER");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("LAST_NAME");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Privacy", "Cafeservello.Modules.Domain.Users.Entities.User.Privacy#Privacy", b1 =>
                        {
                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("PASSWORD");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("USER_NAME");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "Cafeservello.Modules.Domain.Users.Entities.User.Settings#Settings", b1 =>
                        {
                            b1.Property<int>("Themes")
                                .HasColumnType("int")
                                .HasColumnName("THEME");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cafeservello.Modules.Domain.Users.Entities.User", b =>
                {
                    b.HasOne("Cafeservello.Modules.Domain.Users.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_PROFILE");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
